### ISSUE TITLE
Retrieve president from database

### ISSUE THREAD

**Issue by Fedesky25** [PoliTo-Rocket-Team/website-new#6]
Currently, the data about the president in the `about/current-team` page is hardcoded. It should be instead retrieved from Supabase. This also requires the definition of function on the website that retrieves the data of the latest president from the `presidents` table.

**Comment by huseyingulec** [comment]
I just wrote a sql function `get_latest_president` that returns president's id, name, surname, linkedin infos. I had a problem while creating server load functions. I will try to check in my free time.

**Comment by Fedesky25** [comment]
I think you can leverage the function `get_president` (which we might as well rename `get_president_id`) which returns the id of the the current president. For the load function, You can do something similar to what is already there:
```ts
export const load: PageServerLoad = async ({ locals }) => {
    const res = await locals.supabase.rpc("get_complete_subteams");
    if (res.error)
        throw error(500, {
            details: res.error.details,
            message: res.error.message,
        });
    // retrieve president
    const president = await supabase.rpc("get_latest_president");
    // do error check similar to the one above
    return {
        subteams: res.data as unknown as CompleteSubteam[],
        ppBucket: locals.supabase.storage.from("people-pics").getPublicUrl("")
            .data.publicUrl,
        // president data
       president,
    };
};
```

**Comment by huseyingulec** [comment]
I didn't use the `get_president` function because I couldn't see any function to pass president's id which gives me president's other data(name, surname etc). That's why I have written a new function to get all data about president. That's basically includes `get_president` function inside of it. If we have easier way to do it, let me know

**Comment by Fedesky25** [comment]
I meant exactly using the `get_president` function inside yours to simplify it
